import { categoryName, iBezirk, overallCondition } from "./types";

export const RETRIEVED_POSTS = [
  {
    link: ["https://www.mottehuehner.de/"],

    igAccounts: [
      {
        description: "",
        name: "motte_huehner",
      },
    ],
    minAge: 0,
    categories: ["Outdoor", "Tiere", "Unter 2"],
    id: 1680559200000,
    tags: ["Tiere", "chicken"],
    image: [
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/04-04-2023%2F2%2F0?alt=media&token=1b024511-b31c-407f-9271-8feec6f6ff7d",
    ],
    address: "",
    title: "Hühnertwiete",
    bezirk: "Altona",
    text: "Just in time for warmer days we finally want to start sharing with you our tipps for what to do with kids of in and around Hamburg.\nOur first stop is Mottenburger Hühnertwiete (@motte_huehner), a great playground with areas for children of all ages, a water fountain as well as a nearby chicken coop where chicken are allowed to be fed and - if you’re lucky - eggs and honey can be bought. It’s located in very child-friendly Ottensen, around 10 minutes from Altona train station. ",
    createdAt: 1680559200000,
  },

  {
    categories: ["Indoor", "Essen/Café", "Geburtstage"],
    image: [
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/04-04-2023%2F3%2F0?alt=media&token=51f8b082-f554-499b-bbce-2302eb34dfff",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/04-04-2023%2F3%2F1?alt=media&token=39850823-deb2-4a12-be53-35cf4e7008c6",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/04-04-2023%2F3%2F2?alt=media&token=93abb72b-d34c-49a4-862b-6a0f8e51c6a8",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/04-04-2023%2F3%2F3?alt=media&token=0b06121d-d8e4-4c1a-9038-82d680da2e13",
    ],
    bezirk: "Hamburg-Mitte",
    title: "Die Halle Hamburg",
    lastUpdate: 1680472800000,

    igAccounts: [
      {
        description: "",
        name: "diehallehamburg",
      },
      {
        description:
          "If you prefer to not wait and watch, right next door you’ll find Hobenköök",
        name: "hobenkoeoekhamburg",
      },
    ],
    createdAt: 1680559200000,
    address: "Stockmeyerstraße 43, 20457 Hamburg",
    id: 1680559201000,
    link: [" https://www.diehalle.hamburg/"],
    minAge: 5,
    text: "We’re hoping that not too far from now we can start posting some outdoor recommendations again. Until then, we are happy to share with you this place which is a little bit of both: Die Halle Hamburg (@diehallehamburg) is a parkour and free running spot in Hamburg’s Oberhafenquartier.\n\nThey offer courses and open trainings (indoor and outdoor) for children starting from 5 years. The set-up is - just like the whole area - industrial, creative and inclusive.\n\nInside there’s a comfy seating area with sofas from where you can overlook the training and the Elbe.\n\nDie Halle is close to HafenCity with ok-ish access by public transport (bus). Parking is easy right in front of the building.\n\nIf you prefer to not wait and watch, right next door you’ll find Hobenköök (@hobenkoeoekhamburg), an urban market hall and restaurant that’s just perfect for a coffee break or buy some veggies.",
    tags: ["diehalle", "mitte", "Indoor", "parkour"],
  },

  {
    text: "Wildpark Schwarze Berge (@wildparkschwarzeberge) is probably the most popular park for wild Tiere so it should not be missing in our list. Here are a few good reasons why a so-called Wildpark is a great alternative to the great Hagenbeck Zoo:\n1) All Tiere are endemic to our climate.\n2) Many of them can actually be fed with food that is provided by the park.\n3) They have a great playground and a high tower from where you can see all the way to Hamburg.\n4) Entry fee is much lower than for the zoo.\nIt takes around 40 minutes to get there either by car or public transport from the center of Hamburg.",
    bezirk: "",
    tags: [],
    id: 1683151202000,
    image: [
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F18%2F0?alt=media&token=f26da948-f2af-43bb-a1d7-ad2a96fa7bac",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F18%2F2?alt=media&token=2e14a37b-f0db-4264-8a8c-e9d1fb8647ea",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F18%2F1?alt=media&token=62647baf-b374-47c3-9908-36c9bb2e5a0b",
    ],
    createdAt: 1683151200000,
    address: "",
    categories: ["Outdoor", "Spielplatz", "Tiere", "Wochenende Ausflüge"],

    link: [],
    title: "Wildpark Schwarze BergeWildpark Schwarze Berge",
    igAccounts: [
      {
        name: "wildparkschwarzeberge",
        description: "",
      },
    ],
  },

  {
    igAccounts: [
      {
        description: "",
        name: "datolehus",
      },
    ],
    image: [
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F17%2F0?alt=media&token=5f6b7794-072f-4ed7-b2b2-d0924dcba839",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F17%2F1?alt=media&token=35c889e7-1ce5-403f-8bfc-ddba506e5a91",
    ],
    text: "Dat Ole Hus (@datolehus) is located close to Neumünster, around 45 minutes by car from Hamburg.\nThis beautiful old house - in Aukrug was built around 1700 and can be visited as a private musuem. There’s no entrance fee. In the weekends they offer guided tours for 2.- euros per person (1.- euro for children).\nHighlight: the café offers homemade waffles that are prepared on old wood stoves - just like they did 150 years ago. They are come with Rote Grütze and cream, and coffee or juice. For reservations inside it’s recommended to call them before, otherwise they serve everything in the beautiful garden.",
    id: 1683151203000,
    title: "Dat ole Hus",
    bezirk: "",

    tags: [],
    createdAt: 1683151200000,
    link: [],

    categories: [
      "Essen/Café",
      "Museum",
      "Outdoor",
      "Kostenlos",
      "Wochenende Ausflüge",
    ],
    address: "",
  },

  {
    link: [],
    title: "Knuffel's Kinderkulturkaufhaus",
    id: 1683151204000,
    image: [
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F16%2F1.jpg?alt=media&token=c60bd476-1c1f-4da4-bf93-1ca6c90d9bb3",
    ],
    categories: ["Shops"],
    lastUpdate: 1683064800000,

    igAccounts: [],
    address: "",
    tags: [],
    bezirk: "Altona",
    text: "Knuffels Kinderkulturkaufhaus is a cute little shop, located in Ottensen (around 7 minutes walking from Altona train station). They sell mostly books for children of all ages but also little toys, gifts and postcards. If you’re looking to find something special and of high quality, you will likely find it here. By the way, it’s right around the corner of Mottenburger Hühnertwiete and Spielplatz Arnoldstrasse. ",
    createdAt: 1683151200000,
  },

  {
    link: [],
    text: "Haus der Natur is home to Verein Jordsand e.V. (@vereinjordsand), an organization with focus on natural conservation in and around Hamburg.\nThe house from 1909 is located in an amazing park with several lakes and some rare beautiful trees. Going for a walk there is already worth the visit but Haus der Natur offers much more: Several spots in- and outside where kids (and grown-ups) can learn more about nature like trees, birds and water. In addition it’s possible to join several free tours and courses that can be found on their website.",

    image: [
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F15%2F0?alt=media&token=d56bb444-0472-48a2-92cb-128179325927",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F15%2F2?alt=media&token=ec3ce969-465a-42a9-93c7-b3e362f9324f",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F15%2F2.jpg?alt=media&token=04fb81c7-d5d8-415d-a1b6-14978e668902",
    ],

    address: "",
    title: "Verein Jordsand",
    createdAt: 1683151200000,
    lastUpdate: 1683064800000,
    igAccounts: [],
    id: 1683151205000,
    bezirk: "Wandsbek",
    categories: ["Outdoor", "Kostenlos"],
    tags: [],
  },

  {
    image: [
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F14%2F0?alt=media&token=d0ca6ef9-91ab-4eb2-b961-f10553c0a0eb",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F14%2F3?alt=media&token=25523a88-63f6-4122-b1ef-f806fadbdfce",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F14%2F4?alt=media&token=9921e8dd-a7ef-4283-aeca-7a8aed7fecda",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F14%2F2?alt=media&token=d413c98e-82ad-49e1-9d73-33607cfd6485",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F14%2F1?alt=media&token=7c30b363-788c-47df-b415-38b382ea43f2",
    ],
    categories: ["Essen/Café", "Outdoor"],
    link: [],
    createdAt: 1683151200000,
    tags: [],
    title: "Herzapfelhof Lühs, Altes Land",
    bezirk: "",
    igAccounts: [
      {
        name: "herzapfelhof_altesland",
        description: "",
      },
    ],

    id: 1683151206000,
    address: "",
    text: "As you might guess from the name Herzapfelhof Lühs (@herzapfelhof_altesland) is famous for its apples. But for those who had enough of strawberries and cannot wait until October, maybe cherry picking is the answer.\nWhile the farm is located a bit outside in Altes Land, around 45 minutes by car or 90 minutes by train from the center of Hamburg, they offer a range of different things to see and do that make it worth a trip. There is a cute shop selling juices, gifts and obviously cherries and apples. They also have a huge café with a nice play area for smaller gifts and plenty of toys.\nCherry tree fields are located around 1000 meters from the parking lot. You can take a hand cart for the kids (or your own stroller) but the way to get there is bumpy. As there is no shade it’s not recommended to walk all the way on a too hot or too rainy day. But once you make it, it’s a fun experience.\nLittle watch-out: It’s 4.50 entry fee for anyone older than 5 years - even if it’s just parents joining their kid(s), plus the price you pay for the cherries. They charged us the full price although we had only 30 minutes left before closing time. So better don’t go too late in the day to have plenty of time.",
  },

  {
    address: "",
    title: "Spielplatz Arnoldstrasse",
    createdAt: 1683151200000,
    text: "So many of you answered “Arnoldstraße” when asked for your favorite playground. So, we guess it’s time to share some pictures of this place with everyone: “Arni” can be found on Google Maps as “Spielplatz Boninstrasse”. It’s located in Ottensen, around 10 minutes from the train station Altona.\nIt has several different play towers with slides for small and bigger kids, a trampoline and a water play area. There is even is a small kiosk with a bathroom. Last but not least it’s only two minutes walking from the playground at Mottenburger Twiete. So in case it’s too crowded you can always go there.",
    igAccounts: [],
    minAge: 0,
    tags: [],
    image: [
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F13%2F1.jpg?alt=media&token=67c98eed-a2a6-431f-967a-eee244cf9dea",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F13%2F2.jpg?alt=media&token=361673f3-8da1-4344-8a13-bd4dd050eaa7",
    ],
    id: 1683151207000,
    lastUpdate: 1685743200000,

    bezirk: "Altona",
    link: [],
    categories: ["Spielplatz", "Outdoor", "Kostenlos", "Unter 2"],
  },

  {
    text: "Gut Wulfsdorf (@gutwulfsdorf), located at the border of Hamburg to Schleswig-Holstein is an ecological farm that can be visited from Monday to Saturday during their opening times.\nIt’s not allowed to pet the Tiere but very interesting to walk around the area. They have cows, pigs, sheep, horses and chicken. There is a little organic supermarket selling local food but also coffee and cake and an outdoor seating area with a sandbox and plenty of toys. It’s not easy to access by public transport (closest train station is Buchenkamp). By car it takes around 30 minutes from the center of Hamburg.",

    bezirk: "Wandsbek",
    title: "Gut Wulfsdorf",
    tags: [],
    categories: ["Essen/Café", "Shops", "Tiere", "Outdoor", "Spielplatz"],
    link: [],
    id: 1683151208000,
    image: [
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F12%2F0?alt=media&token=9582f1bc-4e4f-45be-9ed7-d36a78676b69",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F12%2F1?alt=media&token=4fed5fcf-dd48-48e6-acd6-7f7eb8768eff",
    ],
    address: "",
    igAccounts: [
      {
        name: "gutwulfsdorf",
        description: "",
      },
    ],
    createdAt: 1683151200000,
  },

  {
    igAccounts: [
      {
        description: "",
        name: "museumshafen_oevelgoenne",
      },
    ],
    image: [
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F11%2F1.jpg?alt=media&token=ddf4b9a9-323a-4ccd-b847-9e1b7a962744",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F11%2F2.jpg?alt=media&token=2a4b5195-0065-444a-badc-0240ce05150e",
    ],
    id: 1683151209000,
    tags: [],
    link: [],
    text: "It doesn’t have to be an expensive tourist trip if you want to take your kids on a boat tour. All you need is a simple HVV day ticket and off you go: Starting from Landungsbrücken or Altona train station you can either take the ferry or the bus to Museumshafen Övelgönne (@museumshafen_oevelgoenne) where you get to see this cute little light house, some fascinating old sailing ships and take a break at one of the restaurants or Elbstrand (or both).\nFrom there you get on the ferry to Finkenwerder that takes around 30-40 minutes round trip. You can sit either inside or outside and they even have bathrooms. On the way back you can get off at Landungsbrücken and take the train home.",
    address: "",
    categories: ["Indoor", "Museum"],

    bezirk: "Altona",
    createdAt: 1683151200000,

    lastUpdate: 1683064800000,
    title: "Museumshafen Oevelgönne",
  },

  {
    image: [
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F10%2F0?alt=media&token=a72e35d3-f284-4d71-b694-8d7b1441eb57",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F10%2F1?alt=media&token=4222c5f6-6152-46d3-8204-879cbec150dc",
    ],
    address: "",
    minAge: 0,
    title: "Planten un Blomen - Japanischer Garten",
    text: "Today’s guest post from Planen un Blomen is a recommendation from Yumi (@youmeanne) with her two daughters who are 9 and 12 years old:\nPlanten un Blomen is the green heart of Hamburg and offers many different activities for children of all ages. On Sunday afternoons, the largest playground of this park can sometimes be a bit too crowded. In that case it's nice to check out the more quiet areas of the park, like the Japanese garden. A beautiful little water fall and these large stepping stones on the water are a lot of fun for kids.",
    link: [],
    id: 1683151210000,

    igAccounts: [
      {
        description: "Yumi made this recommendation :)",
        name: "youmeanne",
      },
    ],
    categories: ["Outdoor", "Spielplatz", "Kostenlos", "Unter 2"],
    tags: [],
    createdAt: 1683151200000,
    bezirk: "Eimsbüttel",
  },

  {
    text: "At Ponyhof Niendorfer Gehege younger kids (starting from around 2-3 years) get to go on their first pony ride. All you need to bring is a helmet (bike helmet is fine) and they give you a tiny pony to take for a walk. There is no one joining but no experience is needed as the ponies are easy going.\nYou can choose to either go on a short walk which takes around 30 minutes, or a long one which takes up to 60-90 minutes (weekends only the short tour).\nDuring the weekend it gets quite busy so there might be a waiting time. But there is a small café right next to it. ",
    link: [],

    id: 1683151211000,
    bezirk: "Eimsbüttel",
    categories: ["Outdoor", "Essen/Café", "Tiere"],
    tags: [],
    igAccounts: [],
    createdAt: 1683151200000,
    title: "Pony-Hof Niendorfer Gehege",
    address: "",
    image: [
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F9%2F0?alt=media&token=57763272-089d-4a3e-b928-c5417237819e",
    ],
  },

  {
    title: "Tomatenretter",
    id: 1683151212000,

    createdAt: 1683151200000,
    lastUpdate: 1683064800000,
    link: [],
    tags: [],

    text: "Today’s recommendation is not exactly a place for entertainment and yet it is still worth a visit: Tomatenretter e.V. (@tomatenretter) are focused on maintaining the diversity of tomatos.\nDid you know there are more than 20.000 different types of tomatos worldwide but EU food regulations only allow certain types to be sold in shops?\nAt Tomatenretter e.V. you will get to see a lot of them. The farm is located around 30 minutes by car from the city center - in between fields of wild flowers and lakes.\nFrom around August it’s possible to harvest small amounts of tomatos when you visit the farm as a guest. If you become a member for minimum 5 euro per month, you will even get the chance to take care of your own plant and keep its tomatos and crops.\nAs they are not an event place they have limited opening times so always check the website before going there. It’s great to stop on the way to pick flowers but other than that there is not much going on in this area, so food and drinks need to be brought from home.",
    categories: ["Outdoor"],
    image: [
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F8%2F1.jpg?alt=media&token=c80f2f82-f03a-4cab-9584-ee1904047901",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F8%2F2.jpg?alt=media&token=de476bab-3450-4928-b4ff-66e384542c0e",
    ],
    igAccounts: [
      {
        description: "",
        name: "tomatenretter",
      },
    ],
    address: "",
    bezirk: "",
  },

  {
    categories: ["Indoor", "Essen/Café", "Unter 2", "Tiere", "Shops", ,],
    title: "Hagenbeck - Tropen-Aquarium",
    bezirk: "Eimsbüttel",
    tags: [],
    igAccounts: [
      {
        name: "tierpark_hagenbeck",
        description: "",
      },
    ],
    text: "Tropenaquarium in Tierpark Hagenbeck (@tierpark_hagenbeck) is well-known and yet we want to mention it here as a great option for rainy days. It’s not as pricey as the actual zoo but still it’s big enough to spend a few hours with crocodiles, ring-tailed monkeys, plenty of fish and some spectacular photo opportunities.\nAs you can guess it’s pretty warm inside but coats can be kept in a locker. There is also a restaurant that sells simple snacks like fries and ice cream.\nIt’s possible to park nearby but even easier to get there by public transport, being located directly at the train station of U2.\nGood to know: It’s not allowed to bring a stroller. It has to be parked outside.",
    createdAt: 1683151200000,
    image: [
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F7%2F0?alt=media&token=74cb4d3d-e99e-494f-93e1-229c5aa173ee",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F7%2F2.jpg?alt=media&token=793262a5-6700-4065-b21a-e29d4a25b5bf",
    ],
    link: [],

    minAge: 1,
    id: 1683151213000,
    address: "",
    lastUpdate: 1683064800000,
  },

  {
    text: "Museumsdorf Volksdorf (@museumsdorf_volksdorf) is located at the border to Schleswig-Holstein, around 30 minutes from the center of Hamburg.\nUnless there is an event it’s usually for free for children as well as adults. Besides some cute old houses that display life as it was 100 years ago, there are also plenty of farm Tiere like cows, sheep, horses and chicken and a tiny shop with pretty toys and accessories.\nAlmost everything takes place outside so better bring shoes that don’t mind some mud. When it’s warm they serve coffee, softdrinks and waffles or cake in the garden. ",
    tags: [],
    createdAt: 1683151200000,

    image: [
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F6%2F1.jpg?alt=media&token=0f168f70-f0db-4037-8209-a6195547ab1e",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F6%2F2.jpg?alt=media&token=4c936926-4046-42b8-9579-f3cfbc948acf",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F6%2F3.jpg?alt=media&token=2c98b79b-b853-43d8-87ee-c760cf9176f2",
    ],
    bezirk: "Wandsbek",
    id: 1683151214000,
    link: [],
    title: "Museumsdorf Volksdorf",
    categories: ["Outdoor", "Kostenlos", "Tiere", "Essen/Café"],
    minAge: 0,
    address: "",
    igAccounts: [
      {
        name: "museumsdorf_volksdorf",
        description: "",
      },
    ],
    lastUpdate: 1683064800000,
  },

  {
    lastUpdate: 1683064800000,
    text: "Garten der Schmetterlinge (@gartenderschmetterlinge) is located a little outside of Hamburg in Aumühle and can be reached either by car or public transport (each around 30 minutes from the center of Hamburg, plus around 15 minutes from the train station).\nWhile it says butterflies, it’s actually a bit more than that: A pretty garden area outside with a (tiny) playground and a rabbit hutch, different tropical houses with butterflies, caterpillars, turtles, koi fish and a little café and gift shop. All in all it’s a small but great place to go to with toddlers but also younger school kids as there is a lot to play, see and learn. ",
    title: "Garten der Schmetterlinge",
    categories: ["Outdoor", "Indoor", "Tiere", "Essen/Café", "Unter 2"],
    createdAt: 1683151200000,
    image: [
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F5%2F0?alt=media&token=b4ea0cd9-485a-47b1-9f3a-8ad56af0ee22",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F5%2F2?alt=media&token=c2c8ce6a-6163-4447-af63-ba2a932e4379",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F5%2F2.jpg?alt=media&token=55faea43-1c31-4840-865a-ad42753b2c69",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F5%2F4.jpg?alt=media&token=bf577b0a-645f-45c1-9295-6c6c556f8bbb",
    ],
    link: [],
    igAccounts: [
      {
        name: "gartenderschmetterlinge",
        description: "",
      },
    ],
    tags: [],

    id: 1683151215000,
    bezirk: "",
    address: "",
  },

  {
    categories: ["Outdoor", "Essen/Café", "Shops"],
    tags: [],
    minAge: 2,
    address: "",
    igAccounts: [
      {
        description: "",
        name: "erdbeerhof_glantz",
      },
    ],
    id: 1683151216000,
    title: "Erdbeerhof Glantz- Erdbeeren Zum Selbst Pflücken",
    text: "Is it even summer without strawberries? One thing is for sure: They taste twice as good if you pick them yourself. There are plenty of strawberry fields to harvest your own (and eat as many as possible while you do) around Hamburg.\nErdbeerhof Glantz (@erdbeerhof_glantz) is probably the most famous one, being the company behind the little strawberry shaped houses you can find all over Hamburg outside of supermarkets.\nYou can check their website for the field that is closest to you. We went to their headquarters, located in Delingsdorf, around 45 minutes from the center of Hamburg and it’s best to go by car. Don’t forget to bring your hat on a very sunny day. And for those who prefer not to pick themselves, Glantz shop and café are only a few minutes from the field.",
    createdAt: 1683151200000,

    bezirk: "",
    link: [],
    image: [
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F4%2F0?alt=media&token=ebe1d325-5753-484f-b679-dd55e8b15ef6",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F4%2F1?alt=media&token=7aed1432-7d5a-48ae-b1f5-3c7e9890cb17",
    ],
  },

  {
    tags: [],
    link: [],
    image: [
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F3%2F0?alt=media&token=840d00a4-3a2b-4151-b596-14812bfb6ae7",
      "https://firebasestorage.googleapis.com/v0/b/hamburg-kids.appspot.com/o/05-04-2023%2F3%2F1?alt=media&token=56f77543-c902-492f-b11d-748ad11c398d",
    ],
    minAge: 3,
    categories: ["Indoor", "Museum", "Kostenlos"],
    id: 1683151217000,
    title: "Zoologisches Museum Hamburg",
    text: "The Zoological Museum (@museumdernatur.hamburg) is a great place to go on a rainy day with kids starting from 3-4 years. It’s located near the University and can be reached by bus, just a few stops from Dammtor train station.\nThere is no entrance fee for either children or adults. So it can get a bit busy in times. But especially during the week it’s perfect for a visit in the afternoon.",
    address: "",
    igAccounts: [
      {
        description: "",
        name: "museumdernatur.hamburg",
      },
    ],
    lastUpdate: 1691013600000,
    bezirk: "Eimsbüttel",

    createdAt: 1683151200000,
  },
];

export const bezirke: iBezirk[] = [
  "Hamburg-Mitte",
  "Altona",
  "Eimsbüttel",
  "Hamburg-Nord",
  "Wandsbek",
  "Bergedorf",
  "Harburg",
  "Außerhalb Hamburg",
];

export const categoryNames = [
  "Indoor",
  "Outdoor",
  "Wochenende Ausflüge",
  "Kostenlos",
  "Spielplatz",
  "Museum",
  "Unter 2",
  "Tiere",
  "Sport",
  "Geburtstage",
  "Essen/Café",
  "Shops",
];

export const relatedCategories: { [x: string]: categoryName[] } = {
  Indoor: ["Spielplatz", "Museum", "Essen/Café"],
  Outdoor: ["Wochenende Ausflüge", "Spielplatz", "Tiere"],
  Spielplatz: ["Outdoor", "Indoor", "Tiere"],
  Museum: ["Indoor", "Essen/Café", "Outdoor"],
  Shops: ["Essen/Café", "Museum", "Indoor"],
  Kostenlos: ["Essen/Café", "Shops", "Wochenende Ausflüge"],
  "Essen/Café": ["Kostenlos", "Indoor", "Shops"],
  "Unter 2": ["Spielplatz", "Indoor", "Museum"],
  Tiere: ["Outdoor", "Spielplatz", "Wochenende Ausflüge"],
  Geburtstage: ["Shops", "Indoor", "Kostenlos"],
  "Wochenende Ausflüge": ["Outdoor", "Tiere", "Kostenlos"],
};

export const WEATHER_CODES: {
  [x: string]: {
    code: number;
    day: string;
    night: string;
    icon: number;
    overallCondition: overallCondition;
    activity: "Outdoor" | "Indoor" | "Both";
  };
} = {
  "1000": {
    code: 1000,
    day: "Sunny",
    night: "Clear",
    icon: 113,
    overallCondition: "Sunny",
    activity: "Outdoor",
  },
  "1003": {
    code: 1003,
    day: "Partly cloudy",
    night: "Partly cloudy",
    icon: 116,
    overallCondition: "Partly cloudy",
    activity: "Outdoor",
  },
  "1006": {
    code: 1006,
    day: "Cloudy",
    night: "Cloudy",
    icon: 119,
    overallCondition: "Cloudy",
    activity: "Both",
  },
  "1009": {
    code: 1009,
    day: "Overcast",
    night: "Overcast",
    icon: 122,
    overallCondition: "Cloudy",
    activity: "Both",
  },
  "1030": {
    code: 1030,
    day: "Mist",
    night: "Mist",
    icon: 143,
    overallCondition: "Foggy",
    activity: "Indoor",
  },
  "1063": {
    code: 1063,
    day: "Patchy rain possible",
    night: "Patchy rain possible",
    icon: 176,
    overallCondition: "Rainy",
    activity: "Indoor",
  },
  "1066": {
    code: 1066,
    day: "Patchy snow possible",
    night: "Patchy snow possible",
    icon: 179,
    overallCondition: "Rainy",
    activity: "Indoor",
  },
  "1069": {
    code: 1069,
    day: "Patchy sleet possible",
    night: "Patchy sleet possible",
    icon: 182,
    overallCondition: "Rainy",
    activity: "Indoor",
  },
  "1072": {
    code: 1072,
    day: "Patchy freezing drizzle possible",
    night: "Patchy freezing drizzle possible",
    icon: 185,
    overallCondition: "Rainy",
    activity: "Indoor",
  },
  "1087": {
    code: 1087,
    day: "Thundery outbreaks possible",
    night: "Thundery outbreaks possible",
    icon: 200,
    overallCondition: "Stormy",
    activity: "Indoor",
  },
  "1114": {
    code: 1114,
    day: "Blowing snow",
    night: "Blowing snow",
    icon: 227,
    overallCondition: "Snowy",
    activity: "Indoor",
  },
  "1117": {
    code: 1117,
    day: "Blizzard",
    night: "Blizzard",
    icon: 230,
    overallCondition: "Snowy",
    activity: "Indoor",
  },
  "1135": {
    code: 1135,
    day: "Fog",
    night: "Fog",
    icon: 248,
    overallCondition: "Foggy",
    activity: "Indoor",
  },
  "1147": {
    code: 1147,
    day: "Freezing fog",
    night: "Freezing fog",
    icon: 260,
    overallCondition: "Foggy",
    activity: "Indoor",
  },
  "1150": {
    code: 1150,
    day: "Patchy light drizzle",
    night: "Patchy light drizzle",
    icon: 263,
    overallCondition: "Rainy",
    activity: "Indoor",
  },
  "1153": {
    code: 1153,
    day: "Light drizzle",
    night: "Light drizzle",
    icon: 266,
    overallCondition: "Rainy",
    activity: "Indoor",
  },
  "1168": {
    code: 1168,
    day: "Freezing drizzle",
    night: "Freezing drizzle",
    icon: 281,
    overallCondition: "Rainy",
    activity: "Indoor",
  },
  "1171": {
    code: 1171,
    day: "Heavy freezing drizzle",
    night: "Heavy freezing drizzle",
    icon: 284,
    overallCondition: "Rainy",
    activity: "Indoor",
  },
  "1180": {
    code: 1180,
    day: "Patchy light rain",
    night: "Patchy light rain",
    icon: 293,
    overallCondition: "Rainy",
    activity: "Indoor",
  },
  "1183": {
    code: 1183,
    day: "Light rain",
    night: "Light rain",
    icon: 296,
    overallCondition: "Rainy",
    activity: "Indoor",
  },
  "1186": {
    code: 1186,
    day: "Moderate rain at times",
    night: "Moderate rain at times",
    icon: 299,
    overallCondition: "Rainy",
    activity: "Indoor",
  },
  "1189": {
    code: 1189,
    day: "Moderate rain",
    night: "Moderate rain",
    icon: 302,
    overallCondition: "Rainy",
    activity: "Indoor",
  },
  "1192": {
    code: 1192,
    day: "Heavy rain at times",
    night: "Heavy rain at times",
    icon: 305,
    overallCondition: "Rainy",
    activity: "Indoor",
  },
  "1195": {
    code: 1195,
    day: "Heavy rain",
    night: "Heavy rain",
    icon: 308,
    overallCondition: "Rainy",
    activity: "Indoor",
  },
  "1198": {
    code: 1198,
    day: "Light freezing rain",
    night: "Light freezing rain",
    icon: 311,
    overallCondition: "Rainy",
    activity: "Indoor",
  },
  "1201": {
    code: 1201,
    day: "Moderate or heavy freezing rain",
    night: "Moderate or heavy freezing rain",
    icon: 314,
    overallCondition: "Rainy",
    activity: "Indoor",
  },
  "1204": {
    code: 1204,
    day: "Light sleet",
    night: "Light sleet",
    icon: 317,
    overallCondition: "Rainy",
    activity: "Indoor",
  },
  "1207": {
    code: 1207,
    day: "Moderate or heavy sleet",
    night: "Moderate or heavy sleet",
    icon: 320,
    overallCondition: "Rainy",
    activity: "Indoor",
  },
  "1210": {
    code: 1210,
    day: "Patchy light snow",
    night: "Patchy light snow",
    icon: 323,
    overallCondition: "Snowy",
    activity: "Indoor",
  },
  "1213": {
    code: 1213,
    day: "Light snow",
    night: "Light snow",
    icon: 326,
    overallCondition: "Snowy",
    activity: "Indoor",
  },
  "1216": {
    code: 1216,
    day: "Patchy moderate snow",
    night: "Patchy moderate snow",
    icon: 329,
    overallCondition: "Snowy",
    activity: "Indoor",
  },
  "1219": {
    code: 1219,
    day: "Moderate snow",
    night: "Moderate snow",
    icon: 332,
    overallCondition: "Snowy",
    activity: "Indoor",
  },
  "1222": {
    code: 1222,
    day: "Patchy heavy snow",
    night: "Patchy heavy snow",
    icon: 335,
    overallCondition: "Snowy",
    activity: "Indoor",
  },
  "1225": {
    code: 1225,
    day: "Heavy snow",
    night: "Heavy snow",
    icon: 338,
    overallCondition: "Snowy",
    activity: "Indoor",
  },
  "1237": {
    code: 1237,
    day: "Ice pellets",
    night: "Ice pellets",
    icon: 350,
    overallCondition: "Stormy",
    activity: "Indoor",
  },
  "1240": {
    code: 1240,
    day: "Light rain shower",
    night: "Light rain shower",
    icon: 353,
    overallCondition: "Snowy",
    activity: "Indoor",
  },
  "1243": {
    code: 1243,
    day: "Moderate or heavy rain shower",
    night: "Moderate or heavy rain shower",
    icon: 356,
    overallCondition: "Snowy",
    activity: "Indoor",
  },
  "1246": {
    code: 1246,
    day: "Torrential rain shower",
    night: "Torrential rain shower",
    icon: 359,
    overallCondition: "Snowy",
    activity: "Indoor",
  },
  "1249": {
    code: 1249,
    day: "Light sleet showers",
    night: "Light sleet showers",
    icon: 362,
    overallCondition: "Snowy",
    activity: "Indoor",
  },
  "1252": {
    code: 1252,
    day: "Moderate or heavy sleet showers",
    night: "Moderate or heavy sleet showers",
    icon: 365,
    overallCondition: "Snowy",
    activity: "Indoor",
  },
  "1255": {
    code: 1255,
    day: "Light snow showers",
    night: "Light snow showers",
    icon: 368,
    overallCondition: "Snowy",
    activity: "Indoor",
  },
  "1258": {
    code: 1258,
    day: "Moderate or heavy snow showers",
    night: "Moderate or heavy snow showers",
    icon: 371,
    overallCondition: "Snowy",
    activity: "Indoor",
  },
  "1261": {
    code: 1261,
    day: "Light showers of ice pellets",
    night: "Light showers of ice pellets",
    icon: 374,
    overallCondition: "Snowy",
    activity: "Indoor",
  },
  "1264": {
    code: 1264,
    day: "Moderate or heavy showers of ice pellets",
    night: "Moderate or heavy showers of ice pellets",
    icon: 377,
    overallCondition: "Snowy",
    activity: "Indoor",
  },
  "1273": {
    code: 1273,
    day: "Patchy light rain with thunder",
    night: "Patchy light rain with thunder",
    icon: 386,
    overallCondition: "Stormy",
    activity: "Indoor",
  },
  "1276": {
    code: 1276,
    day: "Moderate or heavy rain with thunder",
    night: "Moderate or heavy rain with thunder",
    icon: 389,
    overallCondition: "Stormy",
    activity: "Indoor",
  },
  "1279": {
    code: 1279,
    day: "Patchy light snow with thunder",
    night: "Patchy light snow with thunder",
    icon: 392,
    overallCondition: "Stormy",
    activity: "Indoor",
  },
  "1282": {
    code: 1282,
    day: "Moderate or heavy snow with thunder",
    night: "Moderate or heavy snow with thunder",
    icon: 395,
    overallCondition: "Stormy",
    activity: "Indoor",
  },
} as const;

export const addressPartsArray: Array<"street" | "number" | "PLZ" | "city"> = [
  "street",
  "number",
  "PLZ",
  "city",
];

// icons
// loading
{
  /* <a href="https://storyset.com/people">People illustrations by Storyset</a> */
}
// <a href="https://storyset.com/transport">Transport illustrations by Storyset</a>

export const BEZIRK_TO_STADTTEILE: { [key in iBezirk]: string[] } = {
  "Hamburg-Mitte": [
    "Hamburg-Altstadt",
    "HafenCity",
    "Neustadt",
    "St. Pauli",
    "St. Georg",
    "Hammerbrook",
    "Borgfelde",
    "Hamm",
    "Horn",
    "Billstedt",
    "Billbrook",
    "Rothenburgsort",
    "Veddel",
    "Wilhelmsburg",
    "Kleiner Grasbrook",
    "Steinwerder",
    "Waltershof",
    "Finkenwerder",
    "Neuwerk",
  ],
  Altona: [
    "Altona-Altstadt",
    "Sternschanze",
    "Altona-Nord",
    "Ottensen",
    "Bahrenfeld",
    "Groß Flottbek",
    "Othmarschen",
    "Lurup",
    "Osdorf",
    "Nienstedten",
    "Blankenese",
    "Iserbrook",
    "Sülldorf",
    "Rissen",
  ],
  Eimsbüttel: [
    "Eimsbüttel",
    "Rotherbaum",
    "Harvestehude",
    "Hoheluft-West",
    "Lokstedt",
    "Niendorf",
    "Schnelsen",
    "Eidelstedt",
    "Stellingen",
  ],
  "Hamburg-Nord": [
    "Hoheluft-Ost",
    "Eppendorf",
    "Groß Borstel",
    "Alsterdorf",
    "Winterhude",
    "Uhlenhorst",
    "Hohenfelde",
    "Barmbek-Süd",
    "Dulsberg",
    "Barmbek-Nord",
    "Ohlsdorf",
    "Fuhlsbüttel",
    "Langenhorn",
  ],
  Wandsbek: [
    "Eilbek",
    "Wandsbek",
    "Marienthal",
    "Jenfeld",
    "Tonndorf",
    "Farmsen-Berne",
    "Bramfeld",
    "Steilshoop",
    "Wellingsbüttel",
    "Sasel",
    "Poppenbüttel",
    "Hummelsbüttel",
    "Lemsahl-Mellingstedt",
    "Duvenstedt",
    "Wohldorf-Ohlstedt",
    "Bergstedt",
    "Volksdorf",
    "Rahlstedt",
  ],
  Bergedorf: [
    "Lohbrügge",
    "Bergedorf",
    "Curslack",
    "Altengamme",
    "Neuengamme",
    "Kirchwerder",
    "Ochsenwerder",
    "Reitbrook",
    "Allermöhe",
    "Billwerder",
    "Moorfleet",
    "Tatenberg",
    "Spadenland",
    "Neuallermöhe",
  ],
  Harburg: [
    "Harburg",
    "Neuland",
    "Gut Moor",
    "Wilstorf",
    "Rönneburg",
    "Langenbek",
    "Sinstorf",
    "Marmstorf",
    "Eißendorf",
    "Heimfeld",
    "Moorburg",
    "Altenwerder",
    "Hausbruch",
    "Neugraben-Fischbek",
    "Francop",
    "Neuenfelde",
    "Cranz",
  ],
  "Außerhalb Hamburg": [
    "Ahrensburg",
    "Bargteheide",
    "Bönningstedt",
    "Ellerbek",
    "Halstenbek",
    "Norderstedt",
    "Lüneburg",
    "Pinneberg",
    "Quickborn",
    "Rellingen",
    "Schenefeld",
    "Tangstedt",
    "Andere Orte",
  ],
};

export const STADTTEILE_TO_BEZIRK: { [key: string]: iBezirk } = {
  "Altona-Altstadt": "Altona",
  "Altona-Nord": "Altona",
  Bahrenfeld: "Altona",
  Blankenese: "Altona",
  "Groß Flottbek": "Altona",
  Iserbrook: "Altona",
  Lurup: "Altona",
  Nienstedten: "Altona",
  Osdorf: "Altona",
  Othmarschen: "Altona",
  Sülldorf: "Altona",
  Rissen: "Altona",
  Allermöhe: "Bergedorf",
  Altengamme: "Bergedorf",
  Bergedorf: "Bergedorf",
  Billwerder: "Bergedorf",
  Curslack: "Bergedorf",
  Kirchwerder: "Bergedorf",
  Lohbrügge: "Bergedorf",
  Moorfleet: "Bergedorf",
  Neuallermöhe: "Bergedorf",
  Neuengamme: "Bergedorf",
  Ochsenwerder: "Bergedorf",
  Reitbrook: "Bergedorf",
  Spadenland: "Bergedorf",
  Tatenberg: "Bergedorf",
  Eidelstedt: "Eimsbüttel",
  Eimsbüttel: "Eimsbüttel",
  "Hoheluft-West": "Eimsbüttel",
  "Hoheluft-Ost": "Eimsbüttel",
  Lokstedt: "Eimsbüttel",
  Niendorf: "Eimsbüttel",
  Rotherbaum: "Eimsbüttel",
  Schnelsen: "Eimsbüttel",
  Stellingen: "Eimsbüttel",
  Altstadt: "Hamburg-Mitte",
  Billbrook: "Hamburg-Mitte",
  Billstedt: "Hamburg-Mitte",
  Borgfelde: "Hamburg-Mitte",
  Finkenwerder: "Hamburg-Mitte",
  HafenCity: "Hamburg-Mitte",
  Hamm: "Hamburg-Mitte",
  Hammerbrook: "Hamburg-Mitte",
  Horn: "Hamburg-Mitte",
  "Kleiner Grasbrook": "Hamburg-Mitte",
  Neustadt: "Hamburg-Mitte",
  Neuwerk: "Hamburg-Mitte",
  Rothenburgsort: "Hamburg-Mitte",
  Steinwerder: "Hamburg-Mitte",
  Veddel: "Hamburg-Mitte",
  Waltershof: "Hamburg-Mitte",
  Wilhelmsburg: "Hamburg-Mitte",
  Alsterdorf: "Hamburg-Nord",
  "Barmbek-Nord": "Hamburg-Nord",
  "Barmbek-Süd": "Hamburg-Nord",
  Dulsberg: "Hamburg-Nord",
  Eppendorf: "Hamburg-Nord",
  Fuhlsbüttel: "Hamburg-Nord",
  "Groß Borstel": "Hamburg-Nord",
  Hohenfelde: "Hamburg-Nord",
  Langenhorn: "Hamburg-Nord",
  Ohlsdorf: "Hamburg-Nord",
  Uhlenhorst: "Hamburg-Nord",
  Winterhude: "Hamburg-Nord",
  Altenwerder: "Harburg",
  Cranz: "Harburg",
  Eißendorf: "Harburg",
  Francop: "Harburg",
  "Gut Moor": "Harburg",
  Harburg: "Harburg",
  Hausbruch: "Harburg",
  Heimfeld: "Harburg",
  Langenbek: "Harburg",
  Marmstorf: "Harburg",
  Neuenfelde: "Harburg",
  "Neugraben-Fischbek": "Harburg",
  Neuland: "Harburg",
  Rönneburg: "Harburg",
  Sinstorf: "Harburg",
  Wilstorf: "Harburg",
  Bergstedt: "Wandsbek",
  Bramfeld: "Wandsbek",
  Duvenstedt: "Wandsbek",
  Eilbek: "Wandsbek",
  "Farmsen-Berne": "Wandsbek",
  Hummelsbüttel: "Wandsbek",
  Jenfeld: "Wandsbek",
  "Lemsahl-Mellingstedt": "Wandsbek",
  Marienthal: "Wandsbek",
  Poppenbüttel: "Wandsbek",
  Rahlstedt: "Wandsbek",
  Sasel: "Wandsbek",
  Steilshoop: "Wandsbek",
  Tonndorf: "Wandsbek",
  Volksdorf: "Wandsbek",
  Wandsbek: "Wandsbek",
  Wellingsbüttel: "Wandsbek",
};

export const PLZ_TO_STADTTEIL = {
  "20095": ["Hamburg-Altstadt", "Hammerbrook", "St. Georg"],
  "20097": ["Hamm", "Hammerbrook", "St. Georg"],
  "20099": ["Hamburg-Altstadt", "St. Georg"],
  "20144": ["Eimsbüttel", "Harvestehude", "Hoheluft-Ost", "Rotherbaum"],
  "20146": ["Harvestehude", "Rotherbaum"],
  "20148": ["Harvestehude", "Rotherbaum"],
  "20149": ["Harvestehude", "Rotherbaum"],
  "20249": ["Eppendorf", "Harvestehude", "Hoheluft-Ost"],
  "20251": ["Alsterdorf", "Eppendorf", "Hoheluft-Ost"],
  "20253": [
    "Eimsbüttel",
    "Harvestehude",
    "Hoheluft-Ost",
    "Hoheluft-West",
    "Lokstedt",
  ],
  "20255": ["Eimsbüttel", "Lokstedt", "Stellingen"],
  "20257": [
    "Altona-Nord",
    "Eimsbüttel",
    "Rotherbaum",
    "St. Pauli",
    "Sternschanze",
  ],
  "20259": ["Eimsbüttel"],
  "20354": ["Neustadt", "Rotherbaum", "St. Pauli"],
  "20355": ["Neustadt", "St. Pauli"],
  "20357": [
    "Altona-Nord",
    "Eimsbüttel",
    "Rotherbaum",
    "St. Pauli",
    "Sternschanze",
  ],
  "20359": ["Altona-Altstadt", "Neustadt", "St. Pauli", "Sternschanze"],
  "20457": [
    "Hamburg-Altstadt",
    "HafenCity",
    "Kleiner Grasbrook",
    "Neustadt",
    "Steinwerder",
  ],
  "20459": ["Neustadt"],
  "20535": ["Borgfelde", "Hamm"],
  "20537": ["Borgfelde", "Hamm", "Hammerbrook"],
  "20539": [
    "HafenCity",
    "Kleiner Grasbrook",
    "Rothenburgsort",
    "Veddel",
    "Wilhelmsburg",
  ],
  "21029": ["Altengamme", "Bergedorf", "Curslack"],
  "21031": ["Bergedorf", "Lohbrügge"],
  "21033": ["Bergedorf", "Billwerder", "Lohbrügge"],
  "21035": ["Allermöhe", "Bergedorf", "Billwerder", "Neuallermöhe"],
  "21037": [
    "Allermöhe",
    "Curslack",
    "Kirchwerder",
    "Neuengamme",
    "Ochsenwerder",
    "Reitbrook",
    "Spadenland",
    "Tatenberg",
  ],
  "21039": ["Altengamme", "Bergedorf", "Curslack", "Neuengamme"],
  "21073": ["Eißendorf", "Harburg", "Heimfeld", "Wilstorf"],
  "21075": ["Eißendorf", "Harburg", "Hausbruch", "Heimfeld"],
  "21077": [
    "Eißendorf",
    "Langenbek",
    "Marmstorf",
    "Rönneburg",
    "Sinstorf",
    "Wilstorf",
  ],
  "21079": [
    "Gut Moor",
    "Harburg",
    "Hausbruch",
    "Heimfeld",
    "Langenbek",
    "Moorburg",
    "Neuland",
    "Rönneburg",
    "Sinstorf",
    "Wilstorf",
  ],
  "21107": ["Steinwerder", "Wilhelmsburg"],
  "21109": ["Veddel", "Wilhelmsburg"],
  "21129": [
    "Altenwerder",
    "Cranz",
    "Finkenwerder",
    "Francop",
    "Moorburg",
    "Neuland",
    "Waltershof",
  ],
  "21147": ["Hausbruch", "Neugraben-Fischbek"],
  "21149": ["Hausbruch", "Neugraben-Fischbek"],
  "22041": ["Marienthal", "Tonndorf", "Wandsbek"],
  "22043": ["Jenfeld", "Marienthal", "Tonndorf"],
  "22045": ["Jenfeld", "Tonndorf"],
  "22047": ["Bramfeld", "Tonndorf", "Wandsbek"],
  "22049": ["Dulsberg", "Wandsbek"],
  "22081": ["Barmbek-Süd", "Uhlenhorst"],
  "22083": ["Barmbek-Süd"],
  "22085": ["Barmbek-Süd", "Uhlenhorst"],
  "22087": ["Hamm", "Hohenfelde", "Uhlenhorst"],
  "22089": ["Eilbek", "Hamm", "Hohenfelde", "Marienthal", "Wandsbek"],
  "22111": ["Billstedt", "Hamm", "Horn"],
  "22113": [
    "Allermöhe",
    "Billbrook",
    "Billstedt",
    "Billwerder",
    "Horn",
    "Lohbrügge",
    "Moorfleet",
  ],
  "22115": ["Billstedt", "Lohbrügge"],
  "22117": ["Billstedt"],
  "22119": ["Billstedt", "Horn"],
  "22143": ["Rahlstedt"],
  "22145": ["Farmsen-Berne", "Rahlstedt"],
  "22147": ["Rahlstedt"],
  "22149": ["Rahlstedt", "Tonndorf"],
  "22159": ["Bramfeld", "Farmsen-Berne", "Sasel", "Tonndorf"],
  "22175": ["Bramfeld"],
  "22177": ["Bramfeld", "Steilshoop"],
  "22179": ["Bramfeld"],
  "22297": ["Barmbek-Nord", "Groß Borstel", "Winterhude"],
  "22299": ["Winterhude"],
  "22301": ["Winterhude"],
  "22303": ["Barmbek-Nord"],
  "22305": ["Alsterdorf", "Barmbek-Nord", "Barmbek-Süd", "Winterhude"],
  "22307": ["Barmbek-Nord", "Winterhude"],
  "22309": ["Barmbek-Nord", "Bramfeld", "Ohlsdorf", "Steilshoop"],
  "22335": ["Alsterdorf", "Fuhlsbüttel", "Groß Borstel", "Ohlsdorf"],
  "22337": ["Alsterdorf", "Ohlsdorf"],
  "22339": ["Fuhlsbüttel", "Hummelsbüttel"],
  "22359": ["Bergstedt", "Rahlstedt", "Volksdorf"],
  "22391": [
    "Bramfeld",
    "Hummelsbüttel",
    "Ohlsdorf",
    "Poppenbüttel",
    "Sasel",
    "Wellingsbüttel",
  ],
  "22393": ["Bramfeld", "Poppenbüttel", "Sasel", "Wellingsbüttel"],
  "22395": ["Bergstedt", "Poppenbüttel", "Sasel", "Wohldorf-Ohlstedt"],
  "22397": ["Duvenstedt", "Lemsahl-Mellingstedt", "Wohldorf-Ohlstedt"],
  "22399": ["Hummelsbüttel", "Lemsahl-Mellingstedt", "Poppenbüttel"],
  "22415": ["Fuhlsbüttel", "Hummelsbüttel", "Langenhorn"],
  "22417": ["Hummelsbüttel", "Langenhorn"],
  "22419": ["Langenhorn"],
  "22453": ["Groß Borstel", "Niendorf"],
  "22455": ["Niendorf"],
  "22457": ["Eidelstedt", "Niendorf", "Schnelsen"],
  "22459": ["Niendorf", "Schnelsen"],
  "22523": ["Eidelstedt"],
  "22525": ["Bahrenfeld", "Eidelstedt", "Eimsbüttel", "Lurup", "Stellingen"],
  "22527": ["Eidelstedt", "Eimsbüttel", "Lokstedt", "Stellingen"],
  "22529": [
    "Eppendorf",
    "Groß-Borstel",
    "Hoheluft-West",
    "Lokstedt",
    "Stellingen",
  ],
  "22547": ["Bahrenfeld", "Eidelstedt", "Lurup"],
  "22549": ["Bahrenfeld", "Lurup", "Osdorf"],
  "22559": ["Blankenese"],
  "22587": ["Blankenese", "Nienstedten", "Osdorf", "Rissen", "Sülldorf"],
  "22589": ["Blankenese", "Iserbrook", "Osdorf", "Sülldorf"],
  "22605": ["Bahrenfeld", "Groß Flottbek", "Othmarschen"],
  "22607": ["Bahrenfeld", "Groß Flottbek", "Nienstedten", "Othmarschen"],
  "22609": ["Groß Flottbek", "Nienstedten", "Othmarschen", "Osdorf"],
  "22761": ["Bahrenfeld"],
  "22763": ["Othmarschen", "Ottensen"],
  "22765": ["Altona-Altstadt", "Altona-Nord", "Ottensen"],
  "22767": ["Altona-Altstadt", "Ottensen", "St.Pauli", "Sternschanze"],
  "22769": [
    "Altona-Altstadt",
    "Altona-Nord",
    "Bahrenfeld",
    "Eimsbüttel",
    "St.Pauli",
    "Stellingen",
    "Sternschanze",
  ],
  "27499": ["Neuwerk"],
};
export const STADTTEIL_TO_PLZ = {
  Allermöhe: ["21035", "21037", "22113"],
  Alsterdorf: ["20251", "22297", "22335", "22337"],
  Altengamme: ["21029", "21039"],
  Altenwerder: ["21129"],
  "Altona-Altstadt": ["20359", "22765", "22767", "22769"],
  "Altona-Nord": ["20257", "20357", "22765", "22769"],
  Bahrenfeld: ["22525", "22547", "22549", "22605", "22607", "22761", "22769"],
  "Bahrenfeld Forts.": ["22769"],
  "Barmbek-Nord": ["22297", "22303", "22307", "22309"],
  "Barmbek-Süd": ["22081", "22083", "22085", "22305"],
  Bergedorf: ["21029", "21031", "21033", "21035", "21039"],
  Bergstedt: ["22359", "22395"],
  Billbrook: ["22113"],
  Billstedt: ["22111", "22113", "22115", "22117", "22119"],
  Billwerder: ["21033", "21035", "22113"],
  Blankenese: ["22587", "22589"],
  Borgfelde: ["20535", "20537"],
  Bramfeld: ["22047", "22159", "22175", "22177", "22179", "22309"],
  "Bramfeld Forts.": ["22391", "22393"],
  Cranz: ["21129"],
  Curslack: ["21029", "21037", "21039"],
  Dulsberg: ["22049"],
  Duvenstedt: ["22397"],
  Eidelstedt: ["22457", "22523", "22525", "22527", "22547"],
  Eilbek: ["22089"],
  Eimsbüttel: [
    "20144",
    "20253",
    "20255",
    "20257",
    "20259",
    "20357",
    "22525",
    "22527",
    "22769",
  ],
  "Eimsbüttel Forts.": ["22525", "22527", "22769"],
  Eißendorf: ["21073", "21075", "21077"],
  Eppendorf: ["20249", "20251", "22529"],
  "Farmsen-Berne": ["22159", "22145"],
  Finkenwerder: ["21129"],
  Francop: ["21129"],
  Fuhlsbüttel: ["22335", "22339", "22415"],
  "Groß Borstel": ["22297", "22335", "22453", "22529"],
  "Groß Flottbek": ["22605", "22607", "22609"],
  "Gut Moor": ["21079"],
  HafenCity: ["20457", "20539"],
  "Hamburg-Altstadt": ["20095", "20099", "20457"],
  Hamm: ["20097", "20535", "20537", "22087", "22089", "22111"],
  Hammerbrook: ["20095", "20097", "20537"],
  Harburg: ["21073", "21075", "21079"],
  Harvestehude: ["20144", "20146", "20148", "20149", "20249", "20253"],
  Hausbruch: ["21075", "21079", "21147", "21149"],
  Heimfeld: ["21073", "21075", "21079"],
  "Hoheluft-Ost": ["20144", "20249", "20251", "20253"],
  "Hoheluft-West": ["20253", "20255", "22529"],
  Hohenfelde: ["22087", "22089"],
  Horn: ["22111", "22113", "22119"],
  Hummelsbüttel: ["22339", "22391", "22399", "22145", "22417"],
  Iserbrook: ["22589"],
  Jenfeld: ["22043", "22045"],
  Kirchwerder: ["21037"],
  "Kleiner Grasbrook": ["20257", "20539"],
  Langenbek: ["21077", "21079"],
  Langenhorn: ["22415", "22417", "22419"],
  "Lemsahl-Mellingstedt": ["22397", "22399"],
  Lohbrügge: ["21031", "21033", "22113", "22115"],
  Lokstedt: ["20253", "20255", "22527", "22529"],
  Lurup: ["22525", "22547", "22549"],
  Marienthal: ["22041", "22043", "22089"],
  Marmstorf: ["21077"],
  Moorburg: ["21079", "21129"],
  Moorfleet: ["22113"],
  Neuallermöhe: ["21035"],
  Neuenfelde: ["21129"],
  Neuengamme: ["21037", "21039"],
  "Neugraben-Fischbek": ["21147", "21149"],
  Neuland: ["21079"],
  Neustadt: ["20354", "20355", "20359", "20457", "20459"],
  Neuwerk: ["27499"],
  Niendorf: ["22453", "22455", "22457", "22459"],
  Nienstedten: ["22587", "22607", "22609"],
  Ochsenwerder: ["21037"],
  Ohlsdorf: ["22309", "22335", "22337", "22391"],
  Osdorf: ["22549", "22587", "22589", "22609"],
  Othmarschen: ["22605", "22607", "22609", "22763"],
  Ottensen: ["22763", "22765", "22767"],
  Poppenbüttel: ["22391", "22393", "22395", "22399"],
  Rahlstedt: ["22143", "22145", "22147", "22149", "22359"],
  Reitbrook: ["21037"],
  Rissen: ["22559", "22587"],
  Rönneburg: ["21077", "21079"],
  Rothenburgsort: ["20539"],
  Rotherbaum: ["20144", "20146", "20148", "20149", "20354", "20357"],
  Sasel: ["22159", "22391", "22393", "22395"],
  Schnelsen: ["22457", "22459"],
  Sinstorf: ["21077", "21079"],
  Spadenland: ["21037"],
  "St. Georg": ["20095", "20097", "20099"],
  "St. Pauli": ["20354", "20355", "20357", "20359", "22767", "22769"],
  Steilshoop: ["22177", "22309"],
  Steinwerder: ["20457", "21107"],
  Stellingen: ["20255", "22525", "22527", "22529", "22769"],
  Sternschanze: ["20357", "20359", "22767", "22769"],
  Süllorf: ["22587", "22589"],
  Tatenberg: ["21037"],
  Tonndorf: ["22041", "22043", "22045", "22047", "22149", "22159"],
  Uhlenhorst: ["22081", "22085", "22087"],
  Veddel: ["20539", "21109"],
  Volksdorf: ["22359"],
  Waltershof: ["21129"],
  Wandsbek: ["22041", "22047", "22049", "22089"],
  Wellingsbüttel: ["22391", "22393"],
  Wilhelmsburg: ["20539", "21107", "21109"],
  Wilstorf: ["21073", "21077", "21079"],
  Winterhude: ["22297", "22299", "22301", "22303", "22305"],
  "Wohldorf-Ohlstedt": ["22395", "22397"],
};
